function getMusic(musicSrc) {
        var musicVar = "";
        musicVar += "<link rel=\"stylesheet\" href=\"\/css\/music.css\">";
        musicVar += "<div class=\"music_box\" id=\"music_box\">";
        musicVar += "    <audio id=\"audio\">";
        musicVar += "        <source src=" + musicSrc + ">";
        musicVar += "                type=\"audio\/mpeg\">";
        musicVar += "    <\/audio>";
        musicVar += "    <div class=\"shadows\">";
        musicVar += "        <div class=\"shadow-a face\" id=\"shadows\"><\/div>";
        musicVar += "        <div class=\"shadow-b face\" id=\"shadowsb\"><\/div>";
        musicVar += "        <div class=\"shadow-c face\" id=\"shadowsc\"><\/div>";
        musicVar += "    <\/div>";
        musicVar += "    <div class=\"music\" id=\"radio\">";
        musicVar += "        <div class=\"music_foots\">";
        musicVar += "            <div class=\"foot__shadows\">";
        musicVar += "                <div class=\"foot__shadow\"><\/div>";
        musicVar += "                <div class=\"foot__shadow\"><\/div>";
        musicVar += "                <div class=\"foot__shadow\"><\/div>";
        musicVar += "                <div class=\"foot__shadow\"><\/div>";
        musicVar += "            <\/div>";
        musicVar += "            <div class=\"music_foot\">";
        musicVar += "                <div class=\"foot__front face\"><\/div>";
        musicVar += "                <div class=\"foot__back face\"><\/div>";
        musicVar += "                <div class=\"foot__right face\"><\/div>";
        musicVar += "                <div class=\"foot__left face\"><\/div>";
        musicVar += "                <div class=\"foot__top face\"><\/div>";
        musicVar += "                <div class=\"foot__bottom face\"><\/div>";
        musicVar += "            <\/div>";
        musicVar += "        <\/div>";
        musicVar += "        <div class=\"player\">";
        musicVar += "            <div class=\"player__front face\">";
        musicVar += "                <div class=\"speakers\">";
        musicVar += "                    <div class=\"speaker\">";
        musicVar += "                        <div class=\"speaker__front face\"><\/div>";
        musicVar += "                        <div class=\"speaker__back face\"><\/div>";
        musicVar += "                        <div class=\"speaker__right face\"><\/div>";
        musicVar += "                        <div class=\"speaker__left face\"><\/div>";
        musicVar += "                        <div class=\"speaker__top face\">";
        musicVar += "                            <div class=\"speaker__top-ca face speaker-ca\">♫<\/div>";
        musicVar += "                            <div class=\"speaker__top-cb face speaker-cb\">♪<\/div>";
        musicVar += "                        <\/div>";
        musicVar += "                        <div class=\"speaker__bottom face\"><\/div>";
        musicVar += "                    <\/div>";
        musicVar += "                    <div class=\"speaker\">";
        musicVar += "                        <div class=\"speaker__front face\"><\/div>";
        musicVar += "                        <div class=\"speaker__back face\"><\/div>";
        musicVar += "                        <div class=\"speaker__right face\"><\/div>";
        musicVar += "                        <div class=\"speaker__left face\"><\/div>";
        musicVar += "                        <div class=\"speaker__top face\">";
        musicVar += "                            <div class=\"speaker__top-ca face speaker-ca\">♫<\/div>";
        musicVar += "                            <div class=\"speaker__top-cb face speaker-cb\">♪<\/div>";
        musicVar += "                        <\/div>";
        musicVar += "                        <div class=\"speaker__bottom face\"><\/div>";
        musicVar += "                    <\/div>";
        musicVar += "                    <div class=\"player__text\">ISLU<\/div>";
        musicVar += "                <\/div>";
        musicVar += "            <\/div>";
        musicVar += "            <div class=\"player__back face\"><\/div>";
        musicVar += "            <div class=\"player__right face\"><\/div>";
        musicVar += "            <div class=\"player__left face\"><\/div>";
        musicVar += "            <div class=\"player__top face\"><\/div>";
        musicVar += "            <div class=\"player__bottom face\"><\/div>";
        musicVar += "        <\/div>";
        musicVar += "        <div class=\"playert\" id=\"playert\">";
        musicVar += "            <div class=\"playert-tt\">";
        musicVar += "                <div class=\"playert-tt__front face\"><\/div>";
        musicVar += "                <div class=\"playert-tt__back face\"><\/div>";
        musicVar += "                <div class=\"playert-tt__right face\"><\/div>";
        musicVar += "                <div class=\"playert-tt__left face\"><\/div>";
        musicVar += "                <div class=\"playert-tt__top face\"><\/div>";
        musicVar += "                <div class=\"playert-tt__bottom face\"><\/div>";
        musicVar += "            <\/div>";
        musicVar += "            <div class=\"playert-ta playert-ta1\">";
        musicVar += "                <div class=\"playert-ta__front face\"><\/div>";
        musicVar += "                <div class=\"playert-ta__back face\"><\/div>";
        musicVar += "                <div class=\"playert-ta__right face\"><\/div>";
        musicVar += "                <div class=\"playert-ta__left face\"><\/div>";
        musicVar += "                <div class=\"playert-ta__top face\"><\/div>";
        musicVar += "                <div class=\"playert-ta__bottom face\"><\/div>";
        musicVar += "            <\/div>";
        musicVar += "            <div class=\"playert-ta playert-ta2\">";
        musicVar += "                <div class=\"playert-ta__front face\"><\/div>";
        musicVar += "                <div class=\"playert-ta__back face\"><\/div>";
        musicVar += "                <div class=\"playert-ta__right face\"><\/div>";
        musicVar += "                <div class=\"playert-ta__left face\"><\/div>";
        musicVar += "                <div class=\"playert-ta__top face\"><\/div>";
        musicVar += "                <div class=\"playert-ta__bottom face\"><\/div>";
        musicVar += "            <\/div>";
        musicVar += "            <div class=\"playert-tb playert-tb1\">";
        musicVar += "                <div class=\"playert-tb__front face\"><\/div>";
        musicVar += "                <div class=\"playert-tb__back face\"><\/div>";
        musicVar += "                <div class=\"playert-tb__right face\"><\/div>";
        musicVar += "                <div class=\"playert-tb__left face\"><\/div>";
        musicVar += "                <div class=\"playert-tb__top face\"><\/div>";
        musicVar += "                <div class=\"playert-tb__bottom face\"><\/div>";
        musicVar += "            <\/div>";
        musicVar += "            <div class=\"playert-tb playert-tb2\">";
        musicVar += "                <div class=\"playert-tb__front face\"><\/div>";
        musicVar += "                <div class=\"playert-tb__back face\"><\/div>";
        musicVar += "                <div class=\"playert-tb__right face\"><\/div>";
        musicVar += "                <div class=\"playert-tb__left face\"><\/div>";
        musicVar += "                <div class=\"playert-tb__top face\"><\/div>";
        musicVar += "                <div class=\"playert-tb__bottom face\"><\/div>";
        musicVar += "            <\/div>";
        musicVar += "        <\/div>";
        musicVar += "        <div class=\"parts\">";
        musicVar += "            <div class=\"disc\" id=\"disc\"><\/div>";
        musicVar += "            <div class=\"shadow-disc\"><\/div>";
        musicVar += "            <div class=\"speakers\">";
        musicVar += "                <div class=\"control\">";
        musicVar += "                    <div class=\"control-ta\">";
        musicVar += "                        <div class=\"control-ta__front face\"><\/div>";
        musicVar += "                        <div class=\"control-ta__back face\"><\/div>";
        musicVar += "                        <div class=\"control-ta__right face\"><\/div>";
        musicVar += "                        <div class=\"control-ta__left face\"><\/div>";
        musicVar += "                        <div class=\"control-ta__top face\"><\/div>";
        musicVar += "                        <div class=\"control-ta__bottom face\"><\/div>";
        musicVar += "                    <\/div>";
        musicVar += "                    <div class=\"control-tb\">";
        musicVar += "                        <div class=\"control-tb__front face\"><\/div>";
        musicVar += "                        <div class=\"control-tb__back face\"><\/div>";
        musicVar += "                        <div class=\"control-tb__right face\"><\/div>";
        musicVar += "                        <div class=\"control-tb__left face\"><\/div>";
        musicVar += "                        <div class=\"control-tb__top face\"><\/div>";
        musicVar += "                        <div class=\"control-tb__bottom face\"><\/div>";
        musicVar += "                    <\/div>";
        musicVar += "                    <div class=\"control-range\" id=\"control\">";
        musicVar += "                        <div class=\"control-range__front face\"><\/div>";
        musicVar += "                        <div class=\"control-range__back face\"><\/div>";
        musicVar += "                        <div class=\"control-range__right face\"><\/div>";
        musicVar += "                        <div class=\"control-range__left face\"><\/div>";
        musicVar += "                        <div class=\"control-range__top face\"><\/div>";
        musicVar += "                        <div class=\"control-range__bottom face\"><\/div>";
        musicVar += "                    <\/div>";
        musicVar += "                <\/div>";
        musicVar += "                <div class=\"needle\">";
        musicVar += "                    <div class=\"needle-a\">";
        musicVar += "                        <div class=\"needle-a__front face\"><\/div>";
        musicVar += "                        <div class=\"needle-a__back face\"><\/div>";
        musicVar += "                        <div class=\"needle-a__right face\"><\/div>";
        musicVar += "                        <div class=\"needle-a__left face\"><\/div>";
        musicVar += "                        <div class=\"needle-a__top face\"><\/div>";
        musicVar += "                        <div class=\"needle-a__bottom face\"><\/div>";
        musicVar += "                    <\/div>";
        musicVar += "                    <div class=\"needle-con\" id=\"needle\">";
        musicVar += "                        <div class=\"needle-b\">";
        musicVar += "                            <div class=\"needle-b__front face\"><\/div>";
        musicVar += "                            <div class=\"needle-b__back face\"><\/div>";
        musicVar += "                            <div class=\"needle-b__right face\"><\/div>";
        musicVar += "                            <div class=\"needle-b__left face\"><\/div>";
        musicVar += "                            <div class=\"needle-b__top face\"><\/div>";
        musicVar += "                            <div class=\"needle-b__bottom face\"><\/div>";
        musicVar += "                        <\/div>";
        musicVar += "                        <div class=\"needle-c\">";
        musicVar += "                            <div class=\"needle-c__front face\"><\/div>";
        musicVar += "                            <div class=\"needle-c__back face\"><\/div>";
        musicVar += "                            <div class=\"needle-c__right face\"><\/div>";
        musicVar += "                            <div class=\"needle-c__left face\"><\/div>";
        musicVar += "                            <div class=\"needle-c__top face\"><\/div>";
        musicVar += "                            <div class=\"needle-c__bottom face\"><\/div>";
        musicVar += "                        <\/div>";
        musicVar += "                        <div class=\"needle-d\">";
        musicVar += "                            <div class=\"needle-d__front face\"><\/div>";
        musicVar += "                            <div class=\"needle-d__back face\"><\/div>";
        musicVar += "                            <div class=\"needle-d__right face\"><\/div>";
        musicVar += "                            <div class=\"needle-d__left face\"><\/div>";
        musicVar += "                            <div class=\"needle-d__top face\"><\/div>";
        musicVar += "                            <div class=\"needle-d__bottom face\"><\/div>";
        musicVar += "                        <\/div>";
        musicVar += "                    <\/div>";
        musicVar += "                <\/div>";
        musicVar += "            <\/div>";
        musicVar += "        <\/div>";
        musicVar += "        <div class=\"borders\">";
        musicVar += "            <div class=\"border-ta\">";
        musicVar += "                <div class=\"border-ta__front face\"><\/div>";
        musicVar += "                <div class=\"border-ta__back face\"><\/div>";
        musicVar += "                <div class=\"border-ta__right face\"><\/div>";
        musicVar += "                <div class=\"border-ta__left face\"><\/div>";
        musicVar += "                <div class=\"border-ta__top face\"><\/div>";
        musicVar += "                <div class=\"border-ta__bottom face\"><\/div>";
        musicVar += "            <\/div>";
        musicVar += "            <div class=\"border-tb\">";
        musicVar += "                <div class=\"border-tb__front face\"><\/div>";
        musicVar += "                <div class=\"border-tb__back face\"><\/div>";
        musicVar += "                <div class=\"border-tb__right face\"><\/div>";
        musicVar += "                <div class=\"border-tb__left face\"><\/div>";
        musicVar += "                <div class=\"border-tb__top face\"><\/div>";
        musicVar += "                <div class=\"border-tb__bottom face\"><\/div>";
        musicVar += "            <\/div>";
        musicVar += "        <\/div>";
        musicVar += "    <\/div>";
        musicVar += "<\/div>";
        document.getElementById("live2d").insertAdjacentHTML("afterBegin",musicVar);
    }